reforis-shield: remove translations
Right now, reForis is a little bit ahead and has different versions of
dependencies and if you have a full build, there are issues that
static files are not present in reforis package and languages packages
does not have forisjs.mo.

If you dont have forisjs.mo, you end up with not working reForis.
It crashes with:

AttributeError: 'NullTranslations' object has no attribute 'json_catalog'
      args = ("'NullTranslations' object has no attribute 'json_catalog'",)
      with_traceback = <built-in method with_traceback of AttributeError object>

However, if you build locally reforis and copy those packages on the
router, it works flawlessly.

The issue right now is that reforis and reforis-shield are using the
same shared package languages and they could be different. We decided to remove
translations from reForis Shield. There was also possibility to
have separate language files for reForis, but it should not be
necessary.