turris-timezone: add host depends for l18n
In version 0.2.0, there was added feature to provide list of countries
[1]. There was also added to setup_requires (in setup.py)
dependency/package: l18n. OpenWrt has a problem
issue with it as can be seen below:

Error:
  error: invalid command 'bdist_wheel'
  ----------------------------------------
  ERROR: Failed building wheel for l18n
ERROR: Failed to build one or more wheels

It can be solved by adding host package build depends as described here
[2], which solved it for me so I could compile it.

[1] https://gitlab.nic.cz/turris/foris-controller/turris-timezone/-/commit/0a799a2499df8f1526b48846cb3025b4b3af58e0
[2] https://github.com/openwrt/packages/blob/2edbc4c805d61d859f5e2af84293cdfb051f7f56/lang/python/README.md#installing-host-side-python-packages