ruby-breakpoint: add PKG_BUILD_DEPENDS for ruby
While using faster compilation on our build servers, it says during
compiling ruby-breakpoint:

- Building native extensions. This could take a while...
ERROR:  Error installing breakpoint:
	ERROR: Failed to build gem native extension.

    current directory: /foo/build/staging_dir/hostpkg/lib/ruby/gems/2.6.0/gems/ffi-1.15.0/ext/ffi_c
/foo/build/staging_dir/hostpkg/bin/ruby -I /foo/build/staging_dir/hostpkg/lib/ruby/2.6.0 -r ./siteconf20210324-107765-1onhfe2.rb extconf.rb
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

And in the output, there was also:

- You have to install development tools first.