unbound: add more OpenWrt changes to be in sync
Some packages were failing like libreswan, because:
fatal error: unbound-event.h: No such file or directory
 #include <unbound-event.h> /* from unbound devel */
          ^~~~~~~~~~~~~~~~~
compilation terminated.

This should fix it. While at it, enable libpthread and ipset support for Unbound
as it is enabled in OpenWrt.