nextcloud: add missing php7-mod-filter dependency
it's needed when running nextcloud_install:

    + sudo -u nobody php-cli ./occ maintenance:install ...
    An unhandled exception has been thrown:
    Error: Call to undefined function OC\filter_var() in /srv/www/nextcloud/lib/private/Setup.php:479