tvheadend: update to the latest git version from 2021-05-31
Unfortunately, it seems that there will not be released a new version of
TVHeadend anytime soon, even though there are many changes in master
branch and the tvheadend project was given to another person, we can
update it to the latest development version and remove patches.

I think the advantages of the reason above could be that:
- less bugs (of course), when 4.2.8 was released in January 2019
- more features, more updates!
- bugs can be reported to upstream and they can cooperate

For now, I also added libdvbcsa as dependency otherwise compilation
fails and disable libav.

Fixes also:
src/plumbing/transcoding.c:26:10: fatal error: libavresample/avresample.h: No such file or directory
 #include <libavresample/avresample.h>
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.

Compile tested for Turris MOX, OpenWrt 21.02.
Refresh patch